<a href="https://colab.research.google.com/github/vikashkumar97983282-glitch/machine-learning/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
data = pd.read_csv('users.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          99 non-null     int64
 1   Gender           99 non-null     object
 2   Age              99 non-null     int64
 3   EstimatedSalary  99 non-null     int64
 4   Purchased        99 non-null     int64
dtypes: int64(4), object(1)
memory usage: 4.0+ KB

In [ ]:
data.shape

(99, 5)

In [ ]:
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   12            19000          0
1  15810944    Male   11            20000          0
2  15668575  Female    1            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   10            76000          0

In [ ]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
X = data.iloc[:,[2,3]].values
y = data.iloc[:,4].values

In [ ]:
X.shape

(99, 2)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(79, 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_test

array([[ 0.90497356,  0.34816619],
       [-0.6553876 , -1.16276577],
       [ 1.75607965, -0.33021143],
       [-0.44261108, -0.82357696],
       [-0.37168557,  2.10578091],
       [-0.44261108,  0.2248248 ],
       [-0.6553876 ,  0.87236707],
       [-0.6553876 ,  1.64325072],
       [-0.08798354,  0.77986103],
       [ 0.12479298, -1.10109508],
       [ 2.89088777,  2.53747575],
       [ 0.55034603, -0.08352866],
       [-0.6553876 , -0.02185797],
       [-0.44261108, -0.82357696],
       [-0.44261108,  0.90320241],
       [-0.01705803,  0.65651965],
       [-0.6553876 , -0.42271746],
       [-0.6553876 ,  0.96487311],
       [-0.37168557,  0.81069638],
       [ 3.81291937,  1.79742745]])

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
ypred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred)

0.75